name = "website-solidstart"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
# Add your environment variables here
# VITE_SUPABASE_ANON_KEY = "your_key_here"

